### ISSUE TITLE
Examples of the Navigation features

### ISSUE THREAD

**Issue by davidalpert** [erichexter/twitter.bootstrap.mvc#10]
After installing this nuget package, the one thing I had a hard time grokking from the sample project was the Navigation-related features.

An example would be really useful to show how to set up NavigationRoutes and how those differ from other routes I might define in the application...

For example, it looks like the Navigation related pieces of this package take care of adding the 'active' class to the current route, but how do I define a set of routes "underneath" one of the items on the main menu, or is that against the convention?

**Comment by erichexter** [comment]
Do you mean.. you want to add sub menus to the navigation?

**Comment by davidalpert** [comment]
I can think of a couple of options:
- add a sub menu to the navigation
- add several pages (i.e. a wizard or checkout process) all under the
  same "navigation link" in the main nav bar

probably others...?

An example exercising the current functionality would help answer my
questions about the current implementation and I could contribute to drive
out any additional features I need for my use cases.

**Comment by erichexter** [comment]
The current implementation only accounts for the main navigation menu

**Comment by erichexter** [comment]
this example shows a sub menu.. http://twitter.github.com/bootstrap/examples/carousel.html

**Comment by erichexter** [comment]
Nav route configuration example: https://gist.github.com/4128989

**Comment by davidalpert** [comment]
thanks!
