### ISSUE TITLE
Create layouts for each of these example sites

### ISSUE THREAD

**Issue by erichexter** [erichexter/twitter.bootstrap.mvc#11]
http://twitter.github.com/bootstrap/getting-started.html#examples

right now the basic site is the main layout.

**Comment by davidalpert** [comment]
how would you like them contributed? do you see a different sample project? or additional master views for each of these example layouts? or something else?

**Comment by erichexter** [comment]
I was thinking including them as seperate master views / layouts.  the
sample could then include views that reference those layouts.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by davidalpert** [comment]
sounds good; i'll look into it.

**Comment by erichexter** [comment]
that would be awesome! thanks

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by erichexter** [comment]
this seems about half implemented but it gets the job done for explaining what is possible.
