### ISSUE TITLE
Include code templates that match the (Create/Details/Index) views in ~\Views\Shared

### ISSUE THREAD

**Issue by serra** [erichexter/twitter.bootstrap.mvc#17]
So that when you create a new view, it's layout will match the twitter Bootstrap styles instead of the default mvc 4 ones.

**Comment by erichexter** [comment]
Thats a good idea.

**Comment by serra** [comment]
The templates added in cc389688c68f965d780ec101922d903a33c7da2f are a good start. I do find that I change them for my specific project, but that's not a bad thing since we should consider this a bootstrapper and not an end solution.
