### ISSUE TITLE
Error with Visual Studio 2012

### ISSUE THREAD

**Issue by fernandoacorreia** [erichexter/twitter.bootstrap.mvc#2]
Several build errors with Visual Studio 2012 such as:
- Error 1   Compiling transformation: The type or namespace name 'Web' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)    c:\Users\fernando.correia\AppData\Local\Temp\txqr0h41.0.cs  10  34  
- Error 2   Compiling transformation: The type or namespace name 'MvcTextTemplateHost' could not be found (are you missing a using directive or an assembly reference?) c:\Temp\MvcApplication4\MvcApplication4\CodeTemplates\AddView\CSHTML\BootstrapForm.tt   149 1   MvcApplication4
- Error 3   Extension method must be defined in a top level static class; HtmlHelperExtensions is a nested class    c:\Temp\MvcApplication4\MvcApplication4\BootstrapSupport\ViewHelperExtensions.cs    135 41  MvcApplication4

Steps to reproduce:
- Open Visual Studio 2012 (tested with Microsoft Visual Studio Ultimate 2012 Version 11.0.50727.1 RTMREL)
- Create a new project with ASP.NET MVC 4 Web Application
- Select the Internet Application template
- After project creation, select the command Build | Rebuild Solution
- Verify that the build is successful
- In the Package Manager Console, enter the command "Install-Package twitter.bootstrap.mvc4" (tested with Twitter Bootstrap for ASP.Net MVC 4 1.0.36)
- If prompted by Security Warning, authorize the execution of the text template by clicking OK
- Verify that there are 2 build errors
- Select the command Build | Rebuild Solution
- Verify that now there are 3 build errors (error in ViewHelperExtensions.cs)

**Comment by erichexter** [comment]
I pushed a nuget to address the compile error. The first two.errors are
from the .tt files, The nuget installer changes the build properties of the
file and those errors go away when you manually recompile.  I will look
into scripting the clearing of the error output to eliminate the confusion
around those templates.

**Comment by fernandoacorreia** [comment]
Experience with Twitter Bootstrap for ASP.Net MVC 4 1.0.37   released Friday, November 09, 2012:

After creating the new ASP.NET MVC 4 project, installing twitter.bootstrap.mvc4 and rebuilding there are 3 errors:

Error   1   Compiling transformation: The type or namespace name 'Web' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)    c:\Users\fernando.correia\AppData\Local\Temp\zjdlh4v5.0.cs  10  34  

Error   2   Compiling transformation: The type or namespace name 'MvcTextTemplateHost' could not be found (are you missing a using directive or an assembly reference?) c:\Temp\MvcApplication1123\MvcApplication1123\CodeTemplates\AddView\CSHTML\BootstrapForm.tt 149 1   MvcApplication1123

Error   3   'System.Web.Mvc.HtmlHelper' does not contain a definition for 'Partial' and no extension method 'Partial' accepting a first argument of type 'System.Web.Mvc.HtmlHelper' could be found (are you missing a using directive or an assembly reference?)   C:\Temp\MvcApplication1123\MvcApplication1123\BootstrapSupport\ViewHelperExtensions.cs  139 31  MvcApplication1123

After closing and reopening the solution and doing a rebuild there is 1 error:

Error   1   'System.Web.Mvc.HtmlHelper' does not contain a definition for 'Partial' and no extension method 'Partial' accepting a first argument of type 'System.Web.Mvc.HtmlHelper' could be found (are you missing a using directive or an assembly reference?)   C:\Temp\MvcApplication1123\MvcApplication1123\BootstrapSupport\ViewHelperExtensions.cs  139 31  MvcApplication1123

Adding a reference to System.Web.Mvc.Html.PartialExtensions.Partial in ViewHelperExtensions.cs (using System.Web.Mvc.Html) solves this error.

**Comment by devlife** [comment]
The ViewHelperExtensions.cs error has been fixed.

**Comment by erichexter** [comment]
I merged in the latest pull requests.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by fernandoacorreia** [comment]
As of v.1.0.41 the error in ViewHelperExtensions.cs has been corrected by pull request #3.

To prevent confusion from having 2 different issues in a single report, I opened #6 for the build errors after installing the package. These errors are not specific to Visual Studio 2012, they also happen in 2010, so I'll close this issue as resolved.
