### ISSUE TITLE
BootstrapForm scaffold template, BootstrapSupport using directive seems wrong

### ISSUE THREAD

**Issue by srnux** [erichexter/twitter.bootstrap.mvc#21]
Line 19 in file \CodeTemplates\AddView\CSHTML\BootstrapForm.tt seems wrong.
Should be "@using BootstrapSupport;" instead of "using BootstrapSupport;".

**Comment by erichexter** [comment]
I committed a chance in https://github.com/erichexter/twitter.bootstrap.mvc/commit/c63d694781bcccc0998160280c6f2b41b7e1e26e
