### ISSUE TITLE
Missing Edit.cshtml in Shared folder ?

### ISSUE THREAD

**Issue by mrlux** [erichexter/twitter.bootstrap.mvc#30]
When on the Index page and clicking the edit action u get an error that there was no Edit.cshtml page found.

**Comment by erichexter** [comment]
you need to specify the create view in the View method of your Edit Action
see the highlighted line in the sample.
https://github.com/erichexter/twitter.bootstrap.mvc/blob/master/src/Controllers/HomeController.cs.pp#L52

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by mrlux** [comment]
Thx a lot, maybe something to add in the documentation.
