### ISSUE TITLE
How do you test this?

### ISSUE THREAD

**Issue by devlife** [erichexter/twitter.bootstrap.mvc#4]
If I make a change, how can I test it before pushing the changes?  Also, I was thinking about adding a README.markdown file.  Would you be ok with that?

**Comment by erichexter** [comment]
That would be awesome.. please do.  We can also build up the readme.txt in
the package so that there are some docs when the package is installed.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by devlife** [comment]
Great idea!  And good job on the Nuget package.  I'm a big fan of Bootstrap but found it a bit of a hassle to get it up and running in MVC.

**Comment by erichexter** [comment]
There is a private nuget feed that builds from the master branch.. so the testing is on that package from the feed, after that is good we can elevate the package. 

use this as a nuget feed. http://www.myget.org/F/erichexter/

**Comment by erichexter** [comment]
Does this solve the testing issue?

**Comment by devlife** [comment]
Hey Eric.  Would I just build the package locally and manually upload it?

**Comment by erichexter** [comment]
oh.. wait.. so I have a process to QA a package before it is released to
the main nuget feed.

If I understand you correctly, you want to know how you can create a
package and install it into an empty mvc4 project, so you can manually test
the app and make sure it is working, before you commit it locally, or more
likely before you push your repo upstream and create a pull request..
right?

**Comment by devlife** [comment]
Yes that is right.

**Comment by erichexter** [comment]
I added a build.ps1 script to the root of the project.  if you run that
from powershell.. it will create an output directory.. put three nuget
packages in the folder.. you can then add a nuget source to that folder and
then install those packages into a new project.

We can write a test powershell that can be run from the package manager
console. it would.
1. create a new mvc4 empty project
2. install the nuget packages
3. compile
4. launch the app.

This would take a way the mechanics but we would still need to manually
verify the functionality is working properly.

**Comment by devlife** [comment]
Awesome.  I'll give it a try when I get the chance and add those steps to README

**Comment by erichexter** [comment]
great.. we should have those steps in a _how to contribute_ section.

**Comment by devlife** [comment]
Yeah that sounds great.  At some point I'll add some details as to how the code works for rendering the model, etc.

**Comment by erichexter** [comment]
I added c# project for navigation routes and a unit test project for that code.. It seems like it will have enough complexity in the project to require this.
