### ISSUE TITLE
Support for MVC Areas in NavigationRoutes

### ISSUE THREAD

**Issue by robertdean** [erichexter/twitter.bootstrap.mvc#46]
Given the following MVC Area Registration:

``` c#
    public class AdminAreaRegistration : AreaRegistration
    {
        public override string AreaName
        {
            get
            {
                return "Admin";
            }
        }
        public override void RegisterArea(AreaRegistrationContext context)
        {
            context.MapRoute(
                "Admin_default",
                "Admin/{controller}/{action}/{id}",
                new {controller="main", action = "Index", id = UrlParameter.Optional }
            );
        }
    }
```

and using the following configuration: 

``` c#
  routes.MapNavigationRoute<MainController>("Admin", c=>c.Index());
```

When using 

``` c#
  @Html.Navigation()
```

the extension method will generate the following URL

``` c#
~/main/index
```

Instead of 

``` c#
~/Admin
```

**Comment by erroric** [comment]
+1

**Comment by erroric** [comment]
After couple of hours i had written some working code. If you like it, you can pull it into the project :)
P.S. IRouteWithArea interface can be also implemented in the NavigationRoute class, adding public Area property for it, but behaviour with DataTokens is more correct way I think (look here for AreaHelpers source code: http://forums.asp.net/t/1530007.aspx/1)

**Comment by erichexter** [comment]
Thanks for looking at this.. I am going to play with your implementation.
 I want the default configuration of routes to be as simple as possible so,
I am going to see if I can make the API simpler rather then forcing Areas
to be registered using the full overload.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

On Thu, Jan 24, 2013 at 4:27 PM, Локтионов Алексей <notifications@github.com

**Comment by erichexter** [comment]
support added in the current master branch

**Comment by erroric** [comment]
Actually, not. I have commented, why, inside my pull request.
