### ISSUE TITLE
Runtime Error with jQuery 1.9 and jQuery.Validate.js

### ISSUE THREAD

**Issue by CodeRedPaul** [erichexter/twitter.bootstrap.mvc#53]
Hi Eric

I'm having some problems with this. I've run the package installer directly on an empty MVC 4 site but seem to be getting some severe javascript issues.

I've not made any changes to the code at all.

I've posted a question on Stackoverflow: http://stackoverflow.com/questions/14459651/twitter-bootstrap-for-asp-net-mvc-4-jquery-1-9-and-jquery-validate-js

Would you mind taking a look, please? I can't figure this out myself. :)

Cheers,

Paul.

**Comment by erichexter** [comment]
looks like a version conflict.. Please try forcing an early version of
jquery into the project with the install-package -version command.  I can
change the dependency of the bootstrap package to rely on a range of jquery
versions once we figure out where the breaking change was introduced.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by CodeRedPaul** [comment]
Hi Eric

I solved the main issue by using the jquery migrate js, but the 1st issue was only resolved by me physically removing the jquery-1.9.0.min.map file from the solution.

Thanks for your reply. :)

(And hard work on this!)

Paul.
