### ISSUE TITLE
Align package naming with sirkirby's `twitter.bootstrap.mvc` package

### ISSUE THREAD

**Issue by serra** [erichexter/twitter.bootstrap.mvc#61]
The package naming used by [sirkirby](http://nuget.org/profiles/sirkirby)'s package [`twitter.bootstrap.mvc`](http://nuget.org/packages/Twitter.Bootstrap.MVC/) and [erichexter](http://nuget.org/profiles/erichexter)'s package [`twitter.bootstrap.mvc4`](http://nuget.org/packages/twitter.bootstrap.mvc4/) is confusing. 

I think it would be in everybody's best interest to get this sorted out quickly. The sooner, the better. considering both packages are getting some traction (5k+ downloads in several months).

Chris Kirby (a.k.a. sirkirby at [nuget](http://nuget.org/profiles/sirkirby) & [github](https://github.com/sirkirby) maintains the [`twitter.bootstrap` nuget package](http://nuget.org/packages/Twitter.Bootstrap) (80k+ downloads), on which erichexter's [`twitter.bootstrap.mvc4`](http://nuget.org/packages/twitter.bootstrap.mvc4/) has a dependency.  sirkirby also maintains the [`twitter.bootstrap.mvc`](http://nuget.org/packages/Twitter.Bootstrap.MVC/) package, which adds bundling and minification for `twitter.bootstrap` assets to mvc_4_ projects.

I'm developing an MVC4 app and want to add Twitter Bootstrap. Do I ...

 `PM> Install-Package` [`twitter.bootstrap.mvc4`](http://nuget.org/packages/twitter.bootstrap.mvc4/)

OR 

 `PM> Install-Package` [`twitter.bootstrap.mvc`](http://nuget.org/packages/Twitter.Bootstrap.MVC/) ?

From what I understand from both projects, by inspecting sirkirby's [code and readme](https://github.com/sirkirby/twitter-bootstrap-nuget/tree/master/Twitter.Bootstrap.MVC) and erichexter's [code](https://github.com/erichexter/twitter.bootstrap.mvc) and [documentation](http://lostechies.com/erichexter/2012/11/20/twitter-bootstrap-mvc4-the-template-nuget-package-for-asp-net-mvc4-projects/), the projects only have small overlap: the bundling and minification, and the targeting of mvc4. erichexter's project adds more functionality and is more opinionated. Another difference is the dependencies both projects take.

I think both package meet a need: sirkirby's package targets a developer that _only_ wants to quickly add `twitter.bootstrap` assets whereas erichexter's package targets a developer that wants more.

I hope you guys don't mind raising this issue; some might consider it nitpicking but I don't and I hope the effort I put in writing this issue reflects this. I can think of many ways to resolve this, but it's probably best to leave it up to eric and chris.

**Comment by serra** [comment]
I've open also opened [issue 7](https://github.com/sirkirby/twitter-bootstrap-nuget/issues/7) in [sirkirby/twitter-bootstrap-nuget](https://github.com/sirkirby/twitter-bootstrap-nuget)

**Comment by erichexter** [comment]
I looked through the twtitter.bootstrap.mvc package and the bundling in
.mvc4 is opinionated as well.  I will have a conversation with him and see
what if anything he would like to do with it.  Based on how I want the
bundling to work and bring in the additions of the validation shim.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter
