### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fernandoacorreia** [erichexter/twitter.bootstrap.mvc#7]
The link to http://lostechies.com/erichexter/2012/11/19/twitter-bootstrap-mvc4-the-template-nuget-package-for-asp-net-mvc4-projects/ in the Readme is broken. The site replies with a Not Found page.

**Comment by erichexter** [comment]
I am publishing th post tomorrow morning.

**Comment by erichexter** [comment]
The link is live now.

**Comment by fernandoacorreia** [comment]
Great, thanks.
