### ISSUE TITLE
DropDownList

### ISSUE THREAD

**Issue by kmsameboy** [erichexter/twitter.bootstrap.mvc#8]
Hi.

I can't seem to figure out how to show a dropdown list in the create/edit view. Is there a specific way of doing that? Or any hints on how to implement it?

Thanks.

**Comment by erichexter** [comment]
Are you trying to do this using the built in auto-scaffolding?

If you are, you could make a EditorTemplate for the type you are trying to
make the dropdown for. here is an example of how to do that:
http://stackoverflow.com/questions/6744432/reusable-editor-template-with-dropdownlist-for-business-objects

**Comment by kmsameboy** [comment]
Thanks. That solved it :)
