### ISSUE TITLE
HomeController Not installed

### ISSUE THREAD

**Issue by taylorc** [erichexter/twitter.bootstrap.mvc#9]
In Vs2012, installed package via 'Manage NuGet Packages...'  from context menu. The Home controller was not installed into the project.

**Comment by taylorc** [comment]
Didn't read instructions properly

**Comment by erichexter** [comment]
The home controller is in the samples package. Confirm you installed that
package and make sure there isn't an existing home controller. Nuget will
not overwrite times.
