### ISSUE TITLE
Pulls Bootstrap V3

### ISSUE THREAD

**Issue by schellem** [erichexter/twitter.bootstrap.mvc#97]
I'm no expert but seems that the package(s) are pulling the latest Bootstrap 3.0.0.0 when it should be using earlier version of Bootstrap

**Comment by serra** [comment]
Yes, you are right it references `twitter.bootstrap`, without specifying a version; see the dependency definition in [twitter-bootstrap-mvc.nuspec line 16](https://github.com/erichexter/twitter.bootstrap.mvc/blob/master/src/twitter-bootstrap-mvc.nuspec#L16). We could consider specifying a version < 3.0; [see the nuget versioning](http://docs.nuget.org/docs/reference/nuspec-reference#Specifying_Dependencies_in_version_2.0_and_above) rules on how to do this.

Consider opening a pull request with this change; I'm not really sure about the intended behavior here.

**Comment by schellem** [comment]
I'm just getting into Github and NuGet packaging both along with other things. Anyway I do not yet have the expertise to resolve nor do I know what a Github 'pull request' is at this point. 

I can tell you this, bootstrap 3.0 made significant changes and it 'silently' breaks this package.

**Comment by serra** [comment]
Ah, quickest way then would probably to just edit that in using Github's web UI.

First determine which version of `twitter.bootstrap` does work (I guess [2.3.2](https://www.nuget.org/packages/Twitter.Bootstrap/2.3.2)). Then navigate to https://github.com/erichexter/twitter.bootstrap.mvc/blob/master/src/twitter-bootstrap-mvc.nuspec#L16  and locate the edit button above the file content. Hit is and add in the version number - e.g. `version="2.3.2"`. When you save it, a pull request is automatically created - just follow the on screen instructions if any.

**Comment by serra** [comment]
This way, the maintainers can easily review it and pull it if they agree to the change.

**Comment by MisterJames** [comment]
Thanks folks, I've made this change.

**Comment by schellem** [comment]
Serra ....thanks for the information.

Let me ask a newbie question. How\when does the actual package get updated on the NuGet library now that it has been resolved here?

**Comment by serra** [comment]
For this project, that's a manual step performed by one of the maintainers. I think a staging version is pushed to MyGet, but I'm not sure ... check [the readme here](https://github.com/erichexter/twitter.bootstrap.mvc#preview-releases) and [this job on the codebetter build server](http://teamcity.codebetter.com/viewType.html?buildTypeId=bt676&guest=1) ... on the latter you'll see the changes @MisterJames just performed.

**Comment by erichexter** [comment]
if you guys test out the package from the myget server I can push it to the
main nuget feed.  just send an email to me directly..
eric.hexter@gmail.comto make sure I get it.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

On Wed, Oct 9, 2013 at 9:45 AM, Marijn van der Zee <notifications@github.com

**Comment by schellem** [comment]
Started new VS project and added the twitter.bootstrap.mvc\sample from the MyGet feed and got what I expected this time. The sample works and the T.B 2.3.2 was dependency was properly resolved.

Hope to start contributing once I get some experience around here, quite a different world from SubV and TFS.

**Comment by erichexter** [comment]
Thank you all so much for putting in the effort ! I will publish the
package when I get home tonigjt

On Wednesday, October 9, 2013, schellem wrote:

> Started new VS project and added the twitter.bootstrap.mvc\sample from the
> MyGet feed and got what I expected this time. The sample works and the T.B
> 2.3.2 was dependency was properly resolved.
> 
> Hope to start contributing once I get some experience around here, quite a
> different world from SubV and TFS.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/erichexter/twitter.bootstrap.mvc/issues/97#issuecomment-25985564
> .

## 

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter
