### ISSUE TITLE
Update to use twitter.bootstrap 3

### ISSUE THREAD

**Issue by serra** [erichexter/twitter.bootstrap.mvc#98]
With #97 we fixed the dependency on TB 2.3.2; we should investigate what would be necessary to support TB 3.0.

Note: I've read that [VS 2013](http://www.hanselman.com/blog/DownloadVisualStudio2013WhileYourFeedbackStillMatters.aspx) will come with a twitter bootstrap theme too; might be worth a small investigation.

**Comment by schellem** [comment]
I'm hoping to get some time to investigate this a bit further and also use this as an opportunity to get some GitHub 'workflow' and NuGet packaging experience as well.

Anyway there were a handful of class names that changed in TB 3.0.0 along with CSS\JS file name\location changes.

Do I just click the + link to 'fork' the project and that makes a branch for me?

**Comment by erichexter** [comment]
I just pushed the packages to the main feed. it may take a few minutes for
the process to complete.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by serra** [comment]
@schellem - yes that's the typical way to start a fork. See [this help page for more on forking](https://help.github.com/articles/fork-a-repo), hack away, push to your own repo and [open a pull request](https://help.github.com/articles/using-pull-requests). Just let me know if you need some more help.

**Comment by schellem** [comment]
Reference for upgrading to TB 3.0.0 <a href="http://bootply.com/bootstrap-3-migration-guide">Migration Guide </a> and <a href="http://upgrade-bootstrap.bootply.com/">Upgrade Tool</a>

**Comment by kmiloaguilar** [comment]
@erichexter with the pull request #103 this one is fixed.
